# Generated by Django 5.1.15 on 2026-02-14 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job title (e.g., 'Senior Python Developer').",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "company_name",
                    models.CharField(
                        help_text="Company or organization name.", max_length=200
                    ),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True, help_text="Company website URL (optional)."
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo (optional).",
                        null=True,
                        upload_to="jobs/logos/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed job description.",
                        validators=[django.core.validators.MinLengthValidator(50)],
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        help_text="Job requirements and qualifications.",
                        validators=[django.core.validators.MinLengthValidator(20)],
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="Key responsibilities (optional)."
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True, help_text="Benefits and perks (optional)."
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("remote", "Remote"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior (1-2 years)"),
                            ("mid", "Mid Level (3-5 years)"),
                            ("senior", "Senior (5+ years)"),
                            ("lead", "Lead / Principal"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Job location (e.g., 'Kolkata, India' or 'Remote').",
                        max_length=200,
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(
                        default=False, help_text="Is this a remote position?"
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary (optional).",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary (optional).",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="INR",
                        help_text="Currency code (e.g., INR, USD).",
                        max_length=10,
                    ),
                ),
                (
                    "show_salary",
                    models.BooleanField(
                        default=False, help_text="Display salary range publicly?"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Email for applications.", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone (optional).", max_length=20
                    ),
                ),
                (
                    "application_url",
                    models.URLField(
                        blank=True, help_text="External application URL (optional)."
                    ),
                ),
                (
                    "skills_required",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of required skills."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if applicable)."
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this job posting expires.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Post",
                "verbose_name_plural": "Job Posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
