# Generated by Django 5.1.15 on 2026-02-09 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Sender's name.", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Sender's email address.", max_length=254
                    ),
                ),
                ("message", models.TextField(help_text="The message content.")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the message was submitted.",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the message has been read.",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Sender's IP address (for spam tracking).",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Sender's browser user agent string."
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="contact_con_created_a34646_idx"
                    ),
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="contact_con_is_read_821077_idx",
                    ),
                ],
            },
        ),
    ]
