# Generated by Django 5.1.15 on 2026-02-09 04:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_tag_text",
                    models.CharField(
                        default="Available for opportunities",
                        help_text="Small tag text above the main heading (e.g., 'Available for opportunities').",
                        max_length=200,
                    ),
                ),
                (
                    "hero_greeting",
                    models.CharField(
                        default="Hi, I'm",
                        help_text="Text displayed before your name.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_name",
                    models.CharField(
                        default="Anupam Dutta",
                        help_text="Your name displayed in the hero with gradient styling.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_cta_primary_text",
                    models.CharField(
                        default="Get in Touch",
                        help_text="Primary call-to-action button text.",
                        max_length=100,
                    ),
                ),
                (
                    "hero_cta_primary_url",
                    models.CharField(
                        default="#contact",
                        help_text="URL or anchor for the primary CTA (e.g., '#contact').",
                        max_length=500,
                    ),
                ),
                (
                    "hero_cta_primary_icon",
                    models.CharField(
                        blank=True,
                        default="fas fa-paper-plane",
                        help_text="Font Awesome icon class for primary CTA.",
                        max_length=100,
                    ),
                ),
                (
                    "hero_cta_secondary_text",
                    models.CharField(
                        default="View Projects",
                        help_text="Secondary call-to-action button text.",
                        max_length=100,
                    ),
                ),
                (
                    "hero_cta_secondary_url",
                    models.CharField(
                        default="#projects",
                        help_text="URL or anchor for the secondary CTA.",
                        max_length=500,
                    ),
                ),
                (
                    "hero_cta_secondary_icon",
                    models.CharField(
                        blank=True,
                        default="fas fa-code",
                        help_text="Font Awesome icon class for secondary CTA.",
                        max_length=100,
                    ),
                ),
                (
                    "about_section_label",
                    models.CharField(default="About Me", max_length=100),
                ),
                (
                    "about_section_title",
                    models.CharField(default="Passionate about", max_length=200),
                ),
                (
                    "about_section_title_highlight",
                    models.CharField(
                        default="Innovative Solutions",
                        help_text="The gradient-highlighted part of the section title.",
                        max_length=200,
                    ),
                ),
                (
                    "about_description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Rich text description for the About section.",
                    ),
                ),
                (
                    "skills_section_label",
                    models.CharField(default="Technical Expertise", max_length=100),
                ),
                (
                    "skills_section_title",
                    models.CharField(default="My", max_length=200),
                ),
                (
                    "skills_section_title_highlight",
                    models.CharField(default="Skills", max_length=200),
                ),
                (
                    "experience_section_label",
                    models.CharField(default="Career Path", max_length=100),
                ),
                (
                    "experience_section_title",
                    models.CharField(default="Work", max_length=200),
                ),
                (
                    "experience_section_title_highlight",
                    models.CharField(default="Experience", max_length=200),
                ),
                (
                    "projects_section_label",
                    models.CharField(default="Portfolio", max_length=100),
                ),
                (
                    "projects_section_title",
                    models.CharField(default="Featured", max_length=200),
                ),
                (
                    "projects_section_title_highlight",
                    models.CharField(default="Projects", max_length=200),
                ),
                (
                    "education_section_label",
                    models.CharField(default="Academic Background", max_length=100),
                ),
                (
                    "education_section_title",
                    models.CharField(default="My", max_length=200),
                ),
                (
                    "education_section_title_highlight",
                    models.CharField(default="Education", max_length=200),
                ),
                (
                    "certifications_section_label",
                    models.CharField(default="Achievements", max_length=100),
                ),
                (
                    "certifications_section_title",
                    models.CharField(default="My", max_length=200),
                ),
                (
                    "certifications_section_title_highlight",
                    models.CharField(default="Certifications", max_length=200),
                ),
                (
                    "contact_section_label",
                    models.CharField(default="Get in Touch", max_length=100),
                ),
                (
                    "contact_section_title",
                    models.CharField(default="Let's", max_length=200),
                ),
                (
                    "contact_section_title_highlight",
                    models.CharField(default="Connect", max_length=200),
                ),
                (
                    "contact_heading",
                    models.CharField(
                        default="Let's work together!",
                        help_text="Heading text in the contact info area.",
                        max_length=200,
                    ),
                ),
                (
                    "contact_description",
                    models.TextField(
                        blank=True,
                        default="I'm always interested in hearing about new projects and opportunities. Whether you have a question or just want to say hi, feel free to reach out!",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="anupamdutta27121998.in@gmail.com",
                        help_text="Email address for contact form submissions.",
                        max_length=254,
                    ),
                ),
                (
                    "show_about",
                    models.BooleanField(
                        default=True, verbose_name="Show About Section"
                    ),
                ),
                (
                    "show_skills",
                    models.BooleanField(
                        default=True, verbose_name="Show Skills Section"
                    ),
                ),
                (
                    "show_experience",
                    models.BooleanField(
                        default=True, verbose_name="Show Experience Section"
                    ),
                ),
                (
                    "show_projects",
                    models.BooleanField(
                        default=True, verbose_name="Show Projects Section"
                    ),
                ),
                (
                    "show_education",
                    models.BooleanField(
                        default=True, verbose_name="Show Education Section"
                    ),
                ),
                (
                    "show_certifications",
                    models.BooleanField(
                        default=True, verbose_name="Show Certifications Section"
                    ),
                ),
                (
                    "show_contact",
                    models.BooleanField(
                        default=True, verbose_name="Show Contact Section"
                    ),
                ),
                (
                    "about_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile image for the About section.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HeroTypingText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text to display in the typing animation (e.g., 'Python Backend Engineer').",
                        max_length=200,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_typing_texts",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typing Text",
                "verbose_name_plural": "Typing Texts",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter/X"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("stackoverflow", "Stack Overflow"),
                            ("medium", "Medium"),
                            ("other", "Other"),
                        ],
                        help_text="Social media platform.",
                        max_length=50,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Full URL or mailto: link.", max_length=500
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome icon class (e.g., 'fab fa-linkedin-in').",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Tooltip text on hover.", max_length=100
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_social_links",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter/X"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "display_text",
                    models.CharField(
                        help_text="Text displayed for this contact method.",
                        max_length=200,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Full URL, mailto:, or tel: link.", max_length=500
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome icon class (e.g., 'fas fa-envelope').",
                        max_length=100,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Link",
                "verbose_name_plural": "Contact Links",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AboutStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="The statistic value (e.g., '2+', '10+', '6+').",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Description of the statistic (e.g., 'Years Experience').",
                        max_length=100,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_stats",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Statistic",
                "verbose_name_plural": "About Statistics",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Anupam Dutta",
                        help_text="The site name displayed in the browser tab and SEO.",
                        max_length=255,
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        blank=True,
                        default="Python Backend Engineer & GenAI Specialist",
                        max_length=500,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="Anupam Dutta - Python Backend Engineer & Generative AI Specialist. Expert in FastAPI, LangChain, LangGraph, and scalable backend development.",
                        max_length=500,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        default="Python Developer, Backend Engineer, GenAI, LLM Engineer, FastAPI, LangChain",
                        max_length=500,
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics measurement ID (e.g., G-XXXXXXXXXX).",
                        max_length=50,
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        default="Anupam Dutta. All Rights Reserved.",
                        max_length=500,
                    ),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Favicon for the browser tab.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site logo displayed in the navigation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
