# Generated by Django 5.1.15 on 2026-02-09 04:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introduction text displayed at the top of the blog listing.",
                    ),
                ),
                (
                    "posts_per_page",
                    models.PositiveIntegerField(
                        default=10, help_text="Number of posts to display per page."
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(help_text="Publication date.")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Brief excerpt for listing pages.",
                        max_length=500,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("code", 3),
                            ("quote", 4),
                            ("raw_html", 5),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Code snippet"},
                            ),
                            4: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            5: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"help_text": "Use sparingly - raw HTML content."},
                            ),
                        },
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags.", max_length=500
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Featured image for the blog post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
            bases=("wagtailcore.page",),
        ),
    ]
