# Generated by Django 5.1.15 on 2026-02-09 04:31

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Certification name (e.g., 'AWS Cloud Foundations').",
                        max_length=200,
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        help_text="Issuing organization (e.g., 'Amazon Web Services').",
                        max_length=200,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome icon class (e.g., 'fab fa-aws').",
                        max_length=100,
                    ),
                ),
                (
                    "credential_url",
                    models.URLField(
                        blank=True, help_text="URL to verify the credential (optional)."
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True,
                        help_text="Credential ID for verification.",
                        max_length=200,
                    ),
                ),
                (
                    "date_obtained",
                    models.DateField(
                        blank=True,
                        help_text="Date the certification was obtained.",
                        null=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date (leave blank if no expiry).",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this certification from the website.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="Degree title (e.g., 'B.Tech in Computer Science & Engineering').",
                        max_length=200,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="Institution name (e.g., 'JIS College of Engineering').",
                        max_length=200,
                    ),
                ),
                (
                    "institution_url",
                    models.URLField(
                        blank=True, help_text="Institution website URL (optional)."
                    ),
                ),
                (
                    "start_year",
                    models.PositiveIntegerField(help_text="Year of enrollment."),
                ),
                (
                    "end_year",
                    models.PositiveIntegerField(help_text="Year of completion."),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Grade or GPA (e.g., 'GPA: 8.85').",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the education (optional).",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this entry from the website.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-start_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        help_text="Your job title (e.g., 'Jr. Python Developer').",
                        max_length=200,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Company name (e.g., 'Weavers Web Solutions').",
                        max_length=200,
                    ),
                ),
                (
                    "company_url",
                    models.URLField(
                        blank=True, help_text="Company website URL (optional)."
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Work location (e.g., 'Kolkata').",
                        max_length=200,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When you started this position."),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When you left (leave blank for current position).",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is your current position.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Custom ordering (lower numbers first). Default ordering is by start date.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this experience from the website.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Programming Languages').",
                        max_length=200,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome icon class (e.g., 'fas fa-code').",
                        max_length=100,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this category from the website.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "text",
                    models.TextField(help_text="A key achievement or responsibility."),
                ),
                (
                    "experience",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="portfolio.experience",
                    ),
                ),
            ],
            options={
                "verbose_name": "Highlight",
                "verbose_name_plural": "Highlights",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Project title (e.g., 'Plugg - GenAI Matchmaking App').",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief project description (1-2 sentences)."
                    ),
                ),
                (
                    "live_url",
                    models.URLField(
                        blank=True, help_text="URL to the live project (optional)."
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, help_text="URL to the GitHub repository (optional)."
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True,
                        help_text="Featured projects appear on the homepage.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this project from the website.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project thumbnail/logo image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Technology name (e.g., 'Python', 'FastAPI', 'Docker').",
                        max_length=100,
                    ),
                ),
                (
                    "project",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Skill name (e.g., 'Python', 'FastAPI').",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.skillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
